### ISSUE TITLE
whois.unitedtld.com is no longer a whois server

### ISSUE THREAD

**Issue by tmetro** [regru/Net-Whois-Raw#16]
Queries for TLDs like .consulting get sent to whois.unitedtld.com per the lookup table in Net/Whois/Raw/Data.pm. This host seems to no longer respond as a whois server (port 43).

```
% telnet whois.unitedtld.com 43
Trying 198.147.209.137...
Trying 2620:115:3000:5002::137...
telnet: Unable to connect to remote host: Network is unreachable
```

This whois server seems to be part of the donuts.co family, and the whois.donuts.co whois server returns answers for at least some of the TLDs previously mapped to whois.unitedtld.com.

Without getting a statement from donuts.co, or running a comprehensive test suite that performs lookups for every TLD that used to be mapped to whois.unitedtld.com, it is hard to say for sure that substituting whois.donuts.co for the discontinued wois server is safe, but that's what I did locally to repair the issue.

(Is there not a way to retrieve this information dynamically, rather than relying on a static lookup table?)

**Comment by nalobin** [comment]
Fixed in 2.99014
