### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by japharl** [regru/Net-Whois-Raw#25]
Minor documentation issues.

On the documentation page  on meta cpan ( https://metacpan.org/release/Net-Whois-Raw )

The text:
Documentation
**phw**ois	Get Whois information of domains and IP addresses.

should be
pwhois Get Whois information of domains and IP addresses.

Also, on the pwhois pod page ( https://metacpan.org/pod/distribution/Net-Whois-Raw/bin/pwhois ) :
**phw**ois - Get Whois information of domains and IP addresses.

Thank you for the module.  It does exactly what I need, just noticed these minor issues while checking to see what the module can do.

**Comment by mm-david** [comment]
It looks like this [has been resolved](https://github.com/regru/Net-Whois-Raw/commit/613a594a9af8b4e3c8cca127043e9339173b8de1), so the issue can be closed.
